services:
  efcodefirstsample:
    image: ${DOCKER_REGISTRY-}efcodefirstsample
    container_name: api
    build:
      context: .
      dockerfile: EFCodeFirstSample/Dockerfile
    ports:
      - "8080"
      - "8081"

  efcodefirstsample.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=sapass@123
    ports:
      - 1433:1433

  efcodefirstsample.seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80 
